In [1]:
import pandas

In [2]:
l=['rohit','vikas','vishwas','aniket','gamer']

In [3]:
s=[1,2,3,4,5,6]

In [5]:
pandas.DataFrame(s)

0
0  1
1  2
2  3
3  4
4  5
5  6

In [6]:
pandas.Series(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [15]:
a={'first':'1' , 'second':'2' , 'third':'3' , 'fourth':'4','fifth':'5','sixth':'6'}

In [9]:
pandas.Series(a)

first     1
second    2
third     3
fourth    4
dtype: object

In [17]:
pandas.Series(a)

first     1
second    2
third     3
fourth    4
fifth     5
sixth     6
dtype: object

In [32]:
pandas.DataFrame(a['first'])

ValueError: DataFrame constructor not properly called!

In [43]:
import pandas as pd
al={'a':'p','b':'q','c':'r','d':'s','e':'t'}

In [39]:
pd.DataFrame(s[1][3])











TypeError: 'int' object is not subscriptable

In [48]:
r=pd.DataFrame(al)
print(r)

ValueError: If using all scalar values, you must pass an index

In [55]:
r={'a':[1,2,3,4],'b':[5,6,7,8],'c':[1,3,4,6],'d':[4,7,8,9]}

In [56]:
pd.DataFrame(r)

a  b  c  d
0  1  5  1  4
1  2  6  3  7
2  3  7  4  8
3  4  8  6  9

In [67]:
a = pd.DataFrame(r['a'])

In [68]:
print(a)

   0
0  1
1  2
2  3
3  4


In [70]:
pd.read_csv("FL_insurance_sample.csv")

policyID statecode           county  eq_site_limit  hu_site_limit  \
0        119736        FL      CLAY COUNTY       498960.0      498960.00   
1        448094        FL      CLAY COUNTY      1322376.3     1322376.30   
2        206893        FL      CLAY COUNTY       190724.4      190724.40   
3        333743        FL      CLAY COUNTY            0.0       79520.76   
4        172534        FL      CLAY COUNTY            0.0      254281.50   
5        785275        FL      CLAY COUNTY            0.0      515035.62   
6        995932        FL      CLAY COUNTY            0.0    19260000.00   
7        223488        FL      CLAY COUNTY       328500.0      328500.00   
8        433512        FL      CLAY COUNTY       315000.0      315000.00   
9        142071        FL      CLAY COUNTY       705600.0      705600.00   
10       253816        FL      CLAY COUNTY       831498.3      831498.30   
11       894922        FL      CLAY COUNTY            0.0       24059.09   
12       422834        FL      CLAY COUNTY            0.0       48115.94   
13       582721        FL      CLAY COUNTY            0.0       28869.12   
14       842700        FL      CLAY COUNTY            0.0       56135.64   
15       874333        FL      CLAY COUNTY            0.0       48115.94   
16       580146        FL      CLAY COUNTY            0.0       48115.94   
17       456149        FL      CLAY COUNTY            0.0       80192.49   
18       767862        FL      CLAY COUNTY            0.0       48115.94   
19       353022        FL      CLAY COUNTY            0.0       60946.79   
20       367814        FL      CLAY COUNTY            0.0       28869.12   
21       671392        FL      CLAY COUNTY            0.0    13410000.00   
22       772887        FL      CLAY COUNTY            0.0     1669113.93   
23       983122        FL      CLAY COUNTY            0.0      179562.23   
24       934215        FL      CLAY COUNTY            0.0      177744.16   
25       385951        FL      CLAY COUNTY            0.0       17757.58   
26       716332        FL      CLAY COUNTY            0.0      130129.87   
27       751262        FL      CLAY COUNTY            0.0       42854.77   
28       633663        FL      CLAY COUNTY            0.0         785.58   
29       105851        FL      CLAY COUNTY            0.0      170361.91   
...         ...       ...              ...            ...            ...   
36604    792963        FL  PINELLAS COUNTY            0.0      492483.92   
36605    367030        FL  PINELLAS COUNTY            0.0      954000.00   
36606    594660        FL  PINELLAS COUNTY            0.0      900000.00   
36607    360785        FL  PINELLAS COUNTY            0.0     1093500.00   
36608    847570        FL  PINELLAS COUNTY            0.0      436632.30   
36609    196088        FL  PINELLAS COUNTY      1917403.2     1917403.20   
36610    166064        FL  PINELLAS COUNTY      1392346.8     1392346.80   
36611    507269        FL  PINELLAS COUNTY      1175310.0     1175310.00   
36612    335445        FL  PINELLAS COUNTY        47250.9       47250.90   
36613    451921        FL  PINELLAS COUNTY        18630.0       18630.00   
36614    859202        FL  PINELLAS COUNTY         9450.0        9450.00   
36615    584224        FL  PINELLAS COUNTY            0.0      866904.30   
36616    603769        FL  PINELLAS COUNTY            0.0     1541972.70   
36617    575194        FL  PINELLAS COUNTY            0.0     3759303.60   
36618    708726        FL  PINELLAS COUNTY            0.0      717846.30   
36619    645213        FL  PINELLAS COUNTY            0.0     1728847.80   
36620    175829        FL  PINELLAS COUNTY            0.0    24210000.00   
36621    546178        FL  PINELLAS COUNTY            0.0     1331880.30   
36622    938910        FL  PINELLAS COUNTY            0.0       35408.70   
36623    592170        FL  PINELLAS COUNTY            0.0       24574.50   
36624    827844        FL  PINELLAS COUNTY            0

In [72]:
fl=pd.read_csv("FL_insurance_sample.csv")
pd.DataFrame(fl['line'])

line
0      Residential
1      Residential
2      Residential
3      Residential
4      Residential
5      Residential
6       Commercial
7      Residential
8      Residential
9      Residential
10     Residential
11     Residential
12     Residential
13     Residential
14     Residential
15     Residential
16     Residential
17     Residential
18     Residential
19     Residential
20     Residential
21      Commercial
22     Residential
23     Residential
24     Residential
25     Residential
26     Residential
27     Residential
28     Residential
29     Residential
...            ...
36604  Residential
36605  Residential
36606  Residential
36607  Residential
36608  Residential
36609   Commercial
36610  Residential
36611  Residential
36612  Residential
36613  Residential
36614  Residential
36615  Residential
36616  Residential
36617   Commercial
36618  Residential
36619  Residential
36620   Commercial
36621  Residential
36622  Residential
36623  Residential
36624  Residential
36625  Residential
36626  Residential
36627  Residential
36628  Residential
36629  Residential
36630  Residential
36631  Residential
36632  Residential
36633  Residential

[36634 rows x 1 columns]

In [90]:
a=pd.read_csv("FL_insurance_sample.csv",index_col="policyID")
b=a.loc[119736]
c=a.loc[448094]
d=a.iloc[2]
print(b,c,d)

statecode                      FL
county                CLAY COUNTY
eq_site_limit              498960
hu_site_limit              498960
fl_site_limit              498960
fr_site_limit              498960
tiv_2011                   498960
tiv_2012                   792149
eq_site_deductible              0
hu_site_deductible         9979.2
fl_site_deductible              0
fr_site_deductible              0
point_latitude            30.1023
point_longitude          -81.7118
line                  Residential
construction              Masonry
point_granularity               1
Name: 119736, dtype: object statecode                      FL
county                CLAY COUNTY
eq_site_limit         1.32238e+06
hu_site_limit         1.32238e+06
fl_site_limit         1.32238e+06
fr_site_limit         1.32238e+06
tiv_2011              1.32238e+06
tiv_2012              1.43816e+06
eq_site_deductible              0
hu_site_deductible              0
fl_site_deductible              0
fr_site_deductible  

In [92]:
a=pd.read_csv("FL_insurance_sample.csv",index_col="county")
b=a.loc['CLAY COUNTY']
print(b)

             policyID statecode  eq_site_limit  hu_site_limit  fl_site_limit  \
county                                                                         
CLAY COUNTY    119736        FL       498960.0      498960.00       498960.0   
CLAY COUNTY    448094        FL      1322376.3     1322376.30      1322376.3   
CLAY COUNTY    206893        FL       190724.4      190724.40       190724.4   
CLAY COUNTY    333743        FL            0.0       79520.76            0.0   
CLAY COUNTY    172534        FL            0.0      254281.50            0.0   
CLAY COUNTY    785275        FL            0.0      515035.62            0.0   
CLAY COUNTY    995932        FL            0.0    19260000.00            0.0   
CLAY COUNTY    223488        FL       328500.0      328500.00       328500.0   
CLAY COUNTY    433512        FL       315000.0      315000.00       315000.0   
CLAY COUNTY    142071        FL       705600.0      705600.00       705600.0   
CLAY COUNTY    253816        FL       83

In [1]:
import numpy as np

In [7]:
a=np.array([[1,2,3,4,5,6],[2,4,6,8,10],[3,6,9,12,15]])

In [8]:
print(a)

[list([1, 2, 3, 4, 5, 6]) list([2, 4, 6, 8, 10]) list([3, 6, 9, 12, 15])]


In [22]:
b=np.array([[1,3,5],[2,5,7],[3,6,9]])

In [23]:
print(b)

[[1 3 5]
 [2 5 7]
 [3 6 9]]


In [24]:
c=np.array([[1,2],[3,4]])

In [25]:
print(c)

[[1 2]
 [3 4]]


In [26]:
d=np.array([[3,4],[8,9]])

In [27]:
print(d)

[[3 4]
 [8 9]]


In [28]:
add=np.add(c,d)

In [29]:
print(add)

[[ 4  6]
 [11 13]]


In [30]:
aw=np.add(c,1)

In [31]:
print(aw)

[[2 3]
 [4 5]]


In [33]:
a=aw.T

In [34]:
print(a)

[[2 4]
 [3 5]]


In [35]:
e=aw.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [36]:
e=aw.sum()

In [37]:
print(e)

14


In [40]:
x=aw.dtype

In [41]:
print(x)

int32


In [49]:
w=np.sqrt(aw)

In [50]:
print(w)

[[1.41421356 1.73205081]
 [2.         2.23606798]]


In [54]:
s=w.dtype

In [55]:
print(s)

float64


In [56]:
print(aw)

[[2 3]
 [4 5]]
